version: '2.1'
services:
#  sls-go:
#    image: yunspace/serverless-golang:1.25.0
#    env_file: .env
#    volumes:
#      - ./app:${WORKDIR}
#      - ./vendor:${WORKDIR}
#      - ~/.aws:/root/.aws
#    working_dir: ${WORKDIR}

  app:
    build: .
    env_file: .env
    volumes:
      - .:${WORKDIR}
      - ~/.aws:/root/.aws
    working_dir: ${WORKDIR}
#
#  database:
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: password
